### ISSUE TITLE
Fix typos in GitHub Description

### ISSUE THREAD

**Issue by oxinabox** [oxinabox/InternedStrings.jl#22]
As pointed out at
https://github.com/JuliaString/InternedStrings.jl/pull/20#issuecomment-399629315

There are typos in the description on github :blush:
@ScottPJones  It seems I don't gave the privilege to edit repo settings anymore.
I think you might have bumped something by mistake.
Alternatively I've just forgotten how to use github

Description should read (I think)

> Fully transparent string interning functionality, with proper garbage collection

**Comment by ScottPJones** [comment]
Can you check now?
I changed something, about repo level permissions, that I wasn't even aware of before, so you now should have full admin privileges on InternedStrings.
(I can also make you an owner of JuliaString, if you want :grinning:)

**Comment by oxinabox** [comment]
Yep, seems to have worked.
Description is now fixed.

I feel no personal desire to be an owner of JuliaString,
but for Bus-Factor that might be a good idea.

**Comment by ScottPJones** [comment]
Bus-Factor?
I suggested it because 1) you are the author of a package now hosted by JuliaString and 2) I trust your work (well, barring misspellings, but Chris has the same problem also :grinning:, and he's a great guy like you too!)

**Comment by oxinabox** [comment]
Bus-factor as in "if Scott gets hit by a bus does the org collapse?"

**Comment by ScottPJones** [comment]
Oh, true!  Hadn't thought of that!
